# training hyper-parameters
num_epochs : 100
batch_size : 128
dropout_keep_prob : 0.8
clip_value : 100
learning_rate : 0.01
l2 : 0.001
seq_length : 64
optimizer : adagrad
early_stop_step : 50000000
#num_features : 16

# embeddings hyper-parameters
threshold : 0
embedding_size : 100
embedding_normalize : 1

# layers hyper-parameters
hidden_size : 200
attention_size : 200 # no use

# report hyper-parameters
eval_batch : 4000

# IO path
# ## embeddings
vocab_path : ./RWS/clean data/vocab.txt
embedding_path : ./RWS/clean data/embeddings.pkl
#
# ## dataset
load_features : True
trainset_path : ./RWS/clean data/en_train.txt
devset_path : ./RWS/clean data/en_dev.txt
testset_path : ./RWS/clean data/en_dev.txt
#
# ## reports
save_path : ./dense_model_v2/checkpoint
best_path : ./dense_model_v2/bestval
log_path : ./config/log/log
tfboard_path : ./tensorboard
#

## config
config_path : /config/config.yaml

# IO path
## embeddings
#vocab_path : ./SNLI/clean data/vocab.txt
#embedding_path : ./SNLI/clean data/embeddings_300d.pkl

## dataset
#trainset_path : ./SNLI/clean data/train.txt
#devset_path : ./SNLI/clean data/dev.txt
#testset_path : ./SNLI/clean data/test.txt

## reports
#save_path : ./model_v1/checkpoint
#best_path : ./model_v1/bestval
#log_path : ./config/log/log
#tfboard_path : ./tensorboard

